env:
  type: rec_env
  params:
    cold_start: 10
    max_steps: 500
    top_k: 1
    # 시뮬레이션 페르소나 설정 (1-100중 선택, null이면 랜덤)
    persona_id: 5 
    debug: true    # 페르소나 정보 출력 여부

# LLM 시뮬레이터 설정
llm_simulator:
  type: ollama  # random -> ollama로 다시 변경
  params:
    ollama_url: "http://localhost:11434"  # Ollama 서버 주소
    model: "llama3.2:2b"                  # 1b -> 2b로 변경 (더 안정적)
    debug: true                           # false -> true로 변경 (프롬프트 확인)

agent:
  type: dqn
  params:
    lr: 0.001
    batch_size: 32
    eps_start: 1.0
    eps_min: 0.05
    eps_decay: 0.995
    gamma: 0.99
    update_freq: 100

embedder:
  type: simple_concat
  params:
    user_embedder:
      type: simple_user
      params:
        user_dim: 30
    content_embedder:
      type: simple_content
      params:
        content_dim: 5

candidate_generator:
  type: query
  params:
    max_count_by_content: 3

reward_fn:
  type: default
  params: {}

experiment:
  total_episodes: 1
  max_recommendations: 1
  seeds: [0]
  result_log_path: "experiment_results.log"

replay:
  capacity: 10000